name: Daily Congressional Trades Sync

# This workflow syncs congressional trading data daily
# It's FREE on GitHub Actions (2,000 minutes/month on free tier)
# This solves the problem of Render free tier spinning down

on:
  # Run daily at 2:00 AM UTC (9 PM EST)
  schedule:
    - cron: '0 2 * * *'

  # Allow manual trigger from GitHub Actions UI
  workflow_dispatch:
    inputs:
      max_pages:
        description: 'Maximum pages to sync (default: 10)'
        required: false
        default: '10'

jobs:
  sync-trades:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        working-directory: ./backend
        run: npm ci

      - name: Run daily sync
        working-directory: ./backend
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
          NODE_ENV: production
        run: |
          echo "🚀 Starting congressional trades sync..."
          npm run sync:now

      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ Daily sync failed!"
          echo "Check the logs above for error details"
          # Optional: Add Slack/Discord webhook notification here

      - name: Notify on success
        if: success()
        run: |
          echo "✅ Daily sync completed successfully!"

# Alternative: HTTP Trigger (if you prefer)
# Uncomment this job and comment out the one above
#
# trigger-sync-endpoint:
#   runs-on: ubuntu-latest
#   steps:
#     - name: Trigger sync API endpoint
#       run: |
#         curl -X POST "${{ secrets.BACKEND_URL }}/api/v1/admin/sync" \
#           -H "Authorization: Bearer ${{ secrets.ADMIN_API_KEY }}" \
#           -H "Content-Type: application/json" \
#           --fail-with-body || exit 1

# Required GitHub Secrets:
# Go to: Repository Settings → Secrets and variables → Actions → New repository secret
#
# Add these secrets:
# - DATABASE_URL: Your Neon PostgreSQL connection string
# - REDIS_URL: Your Upstash Redis connection string
# - FMP_API_KEY: Your Financial Modeling Prep API key
#
# Optional (for HTTP trigger method):
# - BACKEND_URL: Your Render backend URL
# - ADMIN_API_KEY: A secure API key for admin endpoints
